api-version: 1.19
main: de.IDev.ifh.FFA

name: FFA
version: 1.0
author: I_Dev


commands:
   stats:
   setspawn:
   heal:
   kill:
   deletemessage:
   gamemode:
      aliases: [gm]
   spawn:
   test:
